/**
 * ============================================================================
 * Safety Controller Module (Safety Controller Module)
 * ============================================================================
 * 
 * 【Module responsibility】
 * This module is the safety guardian of the input system，Responsible for immediately clearing all input states in exceptional cases。
 * SafetyController is【Only allowed to trigger clearing】the module，Ensure single authority of clearing operations。
 * 
 * 【Core functionality】
 * 1. Clear permission control: through permission token mechanism，Ensure only authorized modules can trigger clearing
 * 2. Timeout detection: detect state reception timeout，Automatically trigger clearing
 * 3. Exception handling: handle WebSocket disconnect、state exception and other exceptional cases
 * 4. Clear record: record reason, time, permission type of all clearing operations
 * 
 * 【Module boundary】
 * - ✅ Allowed: trigger clearing, manage permission tokens, record clear history, detect timeout
 * - ❌ Prohibited: validate state legality (by Validator)、store state (by StateStore)、generate timestamp (by ApplyScheduler)
 * 
 * 【Clear permission types】
 * - internal: internal clearing，triggered by SafetyController itself（timeout, disconnect etc）
 * - external: external clearing，triggered by external module with valid token
 * - emergency: emergency clearing，no token required, for real emergency situations
 * 
 * 【Time authority】
 * All time-related operations in SafetyController must use tickTime provided by ApplyScheduler：
 * - currentTickTime: updated by ApplyScheduler.updateTickTime()
 * - lastValidStateTime: updated by ApplyScheduler.recordValidState()
 * - Prohibit calling Date.now() for timeout judgment
 * 
 * 【Dependencies】
 * - Dependencies: ExecutorManager (clear execution)、ApplyScheduler (time synchronization)
 * - Depended by: Executor (safety control)、ApplyScheduler (exception handling)
 * 
 * 【Key design】
 * - Single authority pattern: only SafetyController can trigger clearing
 * - Permission token mechanism: external modules need token to request clearing
 * - Time consistency: use ApplyScheduler tickTime to ensure time consistency
 * 
 * 【Notes】
 * - Clearing is highest priority operation, executes immediately
 * - Permission tokens should be properly stored, avoid leakage
 * - Emergency clearing should only be used in real emergency situations
 * 
 * @module input/safetyController
 * @version 2.0.0
 * @last-updated 2026-03-13
 */

import { InputExecutorManager } from "./interfaces";
import { InputState } from "../types/ws";

/**
 * Clear permission token
 * 只有持有Valid令牌the module才能触发清零Operation
 * Token is generated by SafetyController at initialization，distribute to authorized modules
 */
export class ClearPermissionToken {
    private readonly id: string;
    private readonly createdAt: number;
    private isValid: boolean = true;

    constructor(id: string) {
        this.id = id;
        this.createdAt = Date.now();
    }

    getId(): string {
        return this.id;
    }

    getCreatedAt(): number {
        return this.createdAt;
    }

    invalidate(): void {
        this.isValid = false;
    }

    checkValid(): boolean {
        return this.isValid;
    }
}

/**
 * Clear permission types
 */
export type ClearPermission = 'internal' | 'external' | 'emergency';

/**
 * Clear record
 */
interface ClearRecord {
    timestamp: number;
    reason: string;
    permission: ClearPermission;
    tokenId?: string;
}

/**
 * Safety controller config
 */
interface SafetyConfig {
    timeoutMs: number; // Timeout time，Default 500ms
    clearReasons?: Record<string, string>; // Clear reason record
}

/**
 * Safety controller
 * Responsible for exceptional cases（timeout, disconnect, state validation failure etc）Immediately clear all input states
 * SafetyController 是Only allowed to trigger clearingthe module，Ensure single authority of clearing operations
 * 
 * ============================================================================
 * Time authorityDescription
 * ============================================================================
 * All time-related operations in SafetyController must use tickTime provided by ApplyScheduler，
 * Prohibit calling Date.now() to get time，to ensure time consistency。
 * 
 * Time source：
 * - currentTickTime: 由 ApplyScheduler.updateTickTime() Update
 * - lastValidStateTime: 由 ApplyScheduler.recordValidState() Update
 * 
 * Timeout check mechanism：
 * - checkTimeout() uses currentTickTime instead of Date.now()
 * - Trigger clearing when currentTickTime - lastValidStateTime > timeoutMs
 * 
 * Notes：
 * - 在 ApplyScheduler 未启动时，currentTickTime For 0，此时会回退到 Date.now()
 * - 这是临时Compatible机制，正式Run时必须确保 ApplyScheduler 先启动
 * ============================================================================
 */
export class SafetyController {
    // Executor manager reference
    private readonly executorManager: InputExecutorManager;

    // Config
    private readonly config: SafetyConfig;

    // Timestamp of last successful state reception（using ApplyScheduler tickTime）
    private lastValidStateTime: number = 0;

    // Timeout timer
    private timeoutTimer: NodeJS.Timeout | null = null;

    // Clear count
    private clearCount: number = 0;

    // ExceptionClear count
    private exceptionClearCount: number = 0;

    // Destroyed flag
    private isDestroyed: boolean = false;

    // Clear reason record
    private clearReasons: Record<string, string> = {};

    // Current tickTime（provided by ApplyScheduler）
    private currentTickTime: number = 0;

    // Permission token storage
    private readonly permissionTokens: Map<string, ClearPermissionToken> = new Map();

    // Clear recordStore
    private readonly clearRecords: ClearRecord[] = [];

    // MaximumClear record数
    private readonly maxClearRecords: number = 100;

    /**
     * Constructor
     * @param executorManager Executor manager
     * @param config Safety controller config
     */
    constructor(
        executorManager: InputExecutorManager,
        config?: Partial<SafetyConfig>
    ) {
        this.executorManager = executorManager;
        this.config = {
            timeoutMs: 500, // DefaultTimeout time 500ms
            ...config,
        };

        // Create internal permission token（for SafetyController itself）
        this.createPermissionToken('safety-controller-internal', 'internal');

        // No longer auto-start timeout check，Manually started by external call to startTimeoutCheck()
    }

    /**
     * Create permission token
     * Only SafetyController can create tokens，Ensure uniqueness and authority of tokens
     * @param tokenId Token ID
     * @param permission Permission type
     * @returns Permission token
     */
    createPermissionToken(tokenId: string, permission: ClearPermission): ClearPermissionToken {
        const token = new ClearPermissionToken(tokenId);
        this.permissionTokens.set(tokenId, token);
        console.log(`SafetyController: Permission token created: ${tokenId} (${permission})`);
        return token;
    }

    /**
     * VerifyPermission token
     * @param tokenId Token ID
     * @returns Whether token is valid
     */
    validatePermissionToken(tokenId: string): boolean {
        const token = this.permissionTokens.get(tokenId);
        if (!token) {
            console.warn(`SafetyController: Invalid token: ${tokenId}`);
            return false;
        }
        if (!token.checkValid()) {
            console.warn(`SafetyController: Token has been invalidated: ${tokenId}`);
            return false;
        }
        return true;
    }

    /**
     * 撤销Permission token
     * @param tokenId Token ID
     */
    revokePermissionToken(tokenId: string): void {
        const token = this.permissionTokens.get(tokenId);
        if (token) {
            token.invalidate();
            this.permissionTokens.delete(tokenId);
            console.log(`SafetyController: Permission token revoked: ${tokenId}`);
        }
    }

    /**
     * Record clear operation
     * @param reason Clear reason
     * @param permission Permission type
     * @param tokenId Token ID（optional）
     */
    private recordClear(reason: string, permission: ClearPermission, tokenId?: string): void {
        const record: ClearRecord = {
            timestamp: Date.now(),
            reason,
            permission,
            tokenId,
        };

        this.clearRecords.push(record);

        // 限制Record count
        if (this.clearRecords.length > this.maxClearRecords) {
            this.clearRecords.shift();
        }
    }

    /**
     * UpdateCurrent tickTime（Called by ApplyScheduler）
     * ApplyScheduler is the unique time authority，All timestamps come from here
     * @param tickTime Current tick timestamp
     */
    updateTickTime(tickTime: number): void {
        this.currentTickTime = tickTime;
    }

    /**
     * Record valid state reception time
     * @param state Received state
     * @param tickTime tick timestamp（provided by ApplyScheduler，用于时间一致性）
     */
    recordValidState(state: InputState, tickTime: number): void {
        // Use tickTime instead of Date.now()，Ensure time consistency
        this.lastValidStateTime = tickTime;
        this.currentTickTime = tickTime;
        // Remove重复Log，只记录关键Event
    }

    /**
     * Trigger explicit clearing（Internal call，using internal token）
     * @param reason Clear reason
     */
    triggerSafetyClear(reason: string = "explicit"): void {
        this.clearAllInputs();
        this.clearCount++;
        this.clearReasons[this.clearCount] = reason;
        this.recordClear(reason, 'internal', 'safety-controller-internal');
        console.log(
            `SafetyController: Safety clear triggered: ${reason}, total clears: ${this.clearCount}`
        );
    }

    /**
     * Trigger exception clearing（Internal call，using internal token）
     * @param reason Exception原因
     */
    triggerExceptionClear(reason: string): void {
        this.clearAllInputs();
        this.clearCount++;
        this.exceptionClearCount++;
        this.clearReasons[this.clearCount] = reason;
        this.recordClear(reason, 'emergency', 'safety-controller-internal');
        console.log(
            `SafetyController: Exception clear triggered: ${reason}, total clears: ${this.clearCount}, exception clears: ${this.exceptionClearCount}`
        );
    }

    /**
     * Handle explicit zero state（Internal call，using internal token）
     * @param reason Clear reason
     */
    handleZeroState(reason: string = "zero_state"): void {
        this.clearAllInputs();
        this.clearCount++;
        this.clearReasons[this.clearCount] = reason;
        this.recordClear(reason, 'internal', 'safety-controller-internal');
        console.log(
            `SafetyController: Zero state handled: ${reason}, total clears: ${this.clearCount}`
        );
    }

    /**
     * Handle WebSocket disconnect（Internal call，using internal token）
     * @param reason Clear reason
     */
    handleDisconnect(reason: string = "websocket_disconnected"): void {
        this.clearAllInputs();
        this.clearCount++;
        this.clearReasons[this.clearCount] = reason;
        this.recordClear(reason, 'internal', 'safety-controller-internal');
        console.log(
            `SafetyController: WebSocket disconnected: ${reason}, total clears: ${this.clearCount}`
        );
    }

    /**
     * External clear request（需要Permission token）
     * 只有持有Valid令牌the module才能调用此Method
     * @param reason Clear reason
     * @param tokenId 权限Token ID
     * @returns Whether clearing succeeded
     */
    requestClear(reason: string, tokenId: string): boolean {
        if (!this.validatePermissionToken(tokenId)) {
            console.error(`SafetyController: Clear request denied - invalid token: ${tokenId}`);
            return false;
        }

        this.clearAllInputs();
        this.clearCount++;
        this.clearReasons[this.clearCount] = reason;
        this.recordClear(reason, 'external', tokenId);
        console.log(
            `SafetyController: External clear request accepted: ${reason}, token: ${tokenId}, total clears: ${this.clearCount}`
        );
        return true;
    }

    /**
     * Emergency clearing（无需Permission token，用于紧急情况）
     * This method should only be used in real emergency situations
     * @param reason Emergency reason
     */
    emergencyClear(reason: string = "emergency"): void {
        this.clearAllInputs();
        this.clearCount++;
        this.exceptionClearCount++;
        this.clearReasons[this.clearCount] = reason;
        this.recordClear(reason, 'emergency');
        console.log(
            `SafetyController: EMERGENCY clear triggered: ${reason}, total clears: ${this.clearCount}, exception clears: ${this.exceptionClearCount}`
        );
    }

    /**
     * Start timeout check
     */
    startTimeoutCheck(): void {
        // If destroyed, return directly
        if (this.isDestroyed) {
            return;
        }

        // If timer exists, clear first
        if (this.timeoutTimer) {
            clearInterval(this.timeoutTimer);
        }

        // Check timeout every 100ms
        this.timeoutTimer = setInterval(() => {
            this.checkTimeout();
        }, 100);

        console.log(
            `SafetyController: Timeout check started with timeout: ${this.config.timeoutMs}ms`
        );
    }

    /**
     * Check timeout
     * Use tickTime provided by ApplyScheduler for time consistency check
     */
    private checkTimeout(): void {
        // If destroyed, return directly
        if (this.isDestroyed) {
            return;
        }

        // 使用 currentTickTime（provided by ApplyScheduler）而不是 Date.now()
        const now = this.currentTickTime || Date.now();
        const elapsed = now - this.lastValidStateTime;

        if (elapsed > this.config.timeoutMs) {
            this.triggerSafetyClear();
            console.log(
                `SafetyController: Timeout detected, elapsed: ${elapsed}ms, timeout: ${this.config.timeoutMs}ms`
            );
        }
    }

    /**
     * Clear all inputs
     */
    private clearAllInputs(): void {
        // Create zero state
        const zeroState: InputState = {
            keyboard: new Set(),
            mouse: {
                x: 0,
                y: 0,
                left: false,
                right: false,
                middle: false,
            },
            joystick: {
                x: 0,
                y: 0,
                deadzone: 0,
                smoothing: 0,
            },
        };

        // Apply zero state to all executors
        this.executorManager.applyState(zeroState);

        // Call executor reset method，Ensure complete clearing
        this.executorManager.reset();
    }

    /**
     * GetClear count
     * @returns Clear count
     */
    getClearCount(): number {
        return this.clearCount;
    }

    /**
     * GetExceptionClear count
     * @returns ExceptionClear count
     */
    getExceptionClearCount(): number {
        return this.exceptionClearCount;
    }

    /**
     * Get last valid state time
     * @returns Timestamp of last valid state
     */
    getLastValidStateTime(): number {
        return this.lastValidStateTime;
    }

    /**
     * GetClear record
     * @returns Clear recordArray
     */
    getClearRecords(): ClearRecord[] {
        return [...this.clearRecords];
    }

    /**
     * Get最近OfClear record
     * @param count Record count
     * @returns Clear recordArray
     */
    getRecentClearRecords(count: number = 10): ClearRecord[] {
        return this.clearRecords.slice(-count);
    }

    /**
     * Stop timeout check
     */
    stopTimeoutCheck(): void {
        if (this.timeoutTimer) {
            clearInterval(this.timeoutTimer);
            this.timeoutTimer = null;
        }
    }

    /**
     * DestroySafety controller
     */
    destroy(): void {
        // Mark as destroyed
        this.isDestroyed = true;

        // 清除Timeout timer
        this.stopTimeoutCheck();

        // 撤销AllPermission token
        this.permissionTokens.forEach((token, tokenId) => {
            token.invalidate();
        });
        this.permissionTokens.clear();

        console.log(
            "SafetyController: Destroyed, total clears:",
            this.clearCount
        );
    }
}
